### ISSUE TITLE
Did not load on Kodi 20 Ubuntu 20.04

### ISSUE THREAD

**Issue by enigma131** [kodi-pvr/pvr.dvbviewer#158] opened 2023-01-16 07:59 UTC
I downloaded Kodi 20 Rc2 on Windows platform and install it over Kodi 19.5.
I trys tu upgrade the dvbviewer plugin, but got error on intalling it.
Kodi 20 final will go out soon:
https://9to5linux.com/kodi-20-nexus-released-with-av1-hardware-decoding-on-linux-pipewire-support

**Comment by manuelm** [comment] 2023-01-16 08:00
You need to upgrade the PVR as well

**Comment by enigma131** [comment] 2023-01-16 17:44
The PVR upgrades to 20.4.0 under Windows platform and works.
But still no upgrade for Linux (mint 20.3 , Ubuntu 20.04 based)
Strange, it is compiled.. https://launchpad.net/ubuntu/+source/kodi-pvr-dvbviewer

**Comment by globalistas** [comment] 2023-01-19 20:56
> You need to upgrade the PVR as well

Can you please elaborate? I too just run into the issue of DVBViewer Client v19.1.0 being incompatible with Kodi 20 on Windows. There is no update offered to the Client inside Kodi, either.

Thanks!

**Comment by manuelm** [comment] 2023-01-19 23:01
> The PVR upgrades to 20.4.0 under Windows platform and works. But still no upgrade for Linux (mint 20.3 , Ubuntu 20.04 based) Strange, it is compiled.. https://launchpad.net/ubuntu/+source/kodi-pvr-dvbviewer

Ubuntu 20.04 aka Focal Fossa only ships an older version. Same for Kodi. Where did you get the latest Kodi 20 from? You also need to fetch the PVR from this source. Did you install it from ppa:team-xbmc/ppa? It looks like a bunch of addons haven't been updated yet. You can try to fetch the PVR from https://kodi.tv/addons/nexus/pvr.dvbviewer

> Can you please elaborate? I too just run into the issue of DVBViewer Client v19.1.0 being incompatible with Kodi 20 on Windows. There is no update offered to the Client inside Kodi, either.

hu?

![kodi_dvbviewer](https://user-images.githubusercontent.com/357694/213580040-fa843f33-76e8-4718-b412-2e1e3a788d3a.png)

**Comment by globalistas** [comment] 2023-01-20 06:16
![image](https://user-images.githubusercontent.com/64347618/213629712-c6ddbbcf-28ca-4a08-b616-9d2a824a449b.png)

Also, when I try to reinstall the v19.1.0 it fails with 

> 2023-01-20 07:13:55.270 T:40900   error <general>: CAddonInstallJob[pvr.dvbviewer]: The dependency on kodi.binary.global.main version 1.3.0 could not be satisfied

**Comment by globalistas** [comment] 2023-01-20 06:20
Thanks, I had to "Check for updates" on the addon page.

**Comment by enigma131** [comment] 2023-01-20 08:26
My kodi is installed via PPA : https://doc.ubuntu-fr.org/kodi . Without PPA my kodi version will be 18.3, very  old. Via PPA, Kodi 20.0 comes automaticly.
Up to Kodi 19.5 last updated at end december, all was working well.
Who is involved in PPA version compiling ?

**Comment by manuelm** [comment] 2023-01-20 08:59
@wsnipex can you clarify why some PVR packages in `ppa:team-xbmc/ppa` have not been upgraded to their latest release?  https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+packages?field.name_filter=pvr&field.status_filter=published&field.series_filter=focal

**Comment by enigma131** [comment] 2023-01-20 10:20
If  Wolfgang is involved, I have the second one (less used) that is not compiled : kodi.pvr.hts

**Comment by wsnipex** [comment] 2023-01-20 12:55
the issue is: jenkins automatically builds addons  whenever they tag a new release and pushes it to launchpad for each ubuntu series currently supported by kodi. Since ubuntu releases a new series every 6 months, we first have to build kodi for it (jenkins changes) and update our addon pipelines as well.
i.e for dvbviewer the last tagged release was back in september, when e.g. ubuntu 22.10 wasn't released yet. Moreover, kodi's stable branch was still Matrix, so the 20.4.0-Nexus tag was pushed to the nightly PPA. 

The addon pipeline stuff works well for patforms that are hosted in our official repository, but for ubuntu it is  - to say the least - suboptimal.  We'd need some process to automatically build all addons for each current ubuntu series, whenever kodi gets a (major) release (after the new kodi build hits the PPA to be exact)
My time is limited and I've been maintaining the PPAs completely alone, as a sideshow besides the other stuff I do for the project, so this isn't likely to change anytime soon.
Any help would be most welcome...

As for the missing addons: I've now triggered builds for all addons manually, so should be fixed for now.

**Comment by enigma131** [comment] 2023-01-20 14:48
Many thanks wsnipex ! Its working
@Manuelm you can close :+1:

**Closed as completed** 2023-01-20 21:26 UTC
